version: "3"

services:
  # stable-diffusion-discord-bot
  arty:
    build: .
    container_name: arty
    tty: true # enable colorized logs
    restart: always # should this be on-failure ?
    volumes:
      - ./config:/app/config # configuration file and database folder that must persist
    extra_hosts:
      - "host.docker.internal:host-gateway" # Allow refering to host gateway to access rembg (more reliable then hostname?)
    networks:
      - artynet
  # Background removal
  rembg:
    image: "danielgatis/rembg"
    container_name: rembg
    restart: always
    ports:
      - "5000:5000"
    entrypoint: "rembg s"
    networks:
      - artynet
  #artydb:
  #  image: apache/couchdb:latest
  #  container_name: artydb
  #  restart: unless-stopped
  #  ports:
  #    - 5984:5984
  #  volumes:
  #    - artydb:/opt/couchdb/data
  #  environment:
  #    - COUCHDB_USER=admin
  #    - COUCHDB_PASSWORD=changeme
  # networks:
  #    - artynet
  #  entrypoint: "start file:/db/arty.db"
#volumes:
#  artydb:
networks:
  artynet:
    driver: bridge