version: '3'

services:
  discord-bot:
    build: .
    container_name: stable-diffusion-discord-bot
    tty: true
    x-develop:
      watch:
        - action: rebuild
          path: index.js
    volumes:
      - ~/invokeai/outputs:/app/outputs
      - ./config:/app/config
      - ./txt:/app/txt
  rembg:
    image: "danielgatis/rembg"
    ports:
    - "5000"
    entrypoint: "rembg s"
